# Generated by Django 5.2.15 on 2026-07-13 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_alter_organization_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("brd", "Business Requirements"),
                            ("frd", "Functional Requirements"),
                            ("uml", "UML Diagrams"),
                            ("bpmn", "BPMN Processes"),
                            ("swot", "SWOT Analysis"),
                            ("gap", "Gap Analysis"),
                            ("risk", "Risk Management"),
                            ("agile", "Agile/Scrum"),
                            ("compliance", "Compliance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                ("views_count", models.IntegerField(default=0)),
                ("uses_count", models.IntegerField(default=0)),
                ("forks_count", models.IntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_time",
                    models.CharField(
                        blank=True, help_text="e.g., '2 hours', '1 day'", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "templates",
                "ordering": ["-views_count", "-uses_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="templates.template",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "template_reviews",
            },
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["category", "status"], name="templates_categor_3136a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["status", "-views_count"], name="templates_status_26b6ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["created_by"], name="templates_created_1bca30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(fields=["tags"], name="templates_tags_54e72a_idx"),
        ),
        migrations.AddIndex(
            model_name="templatereview",
            index=models.Index(
                fields=["template", "-rating"], name="template_re_templat_96ef73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templatereview",
            index=models.Index(fields=["user"], name="template_re_user_id_41de02_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="templatereview",
            unique_together={("template", "user")},
        ),
    ]
