# Generated by Django 5.2.15 on 2026-07-05 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
        ("projects", "0003_activitylog"),
        ("requirements", "0001_initial"),
        ("risks", "0001_initial"),
        ("stakeholders", "0001_initial"),
        ("stories", "0002_userstory_jira_key_userstory_jira_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("diagram_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=50)),
                ("canvas_json", models.JSONField(blank=True, default=dict)),
                ("documentation", models.TextField(blank=True, default="")),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_diagrams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_diagrams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagrams",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "diagrams",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagramApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                ("version", models.CharField(max_length=50)),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="diagrams.diagram",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagram_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "diagram_approvals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagramComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("text", models.TextField()),
                ("node_id", models.CharField(blank=True, default="", max_length=100)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="diagrams.diagram",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="diagrams.diagramcomment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagram_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "diagram_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagramVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.CharField(max_length=50)),
                ("canvas_json", models.JSONField(default=dict)),
                ("documentation", models.TextField(blank=True, default="")),
                ("status", models.CharField(default="DRAFT", max_length=50)),
                (
                    "checkpoint_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("change_description", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_diagram_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="diagrams.diagram",
                    ),
                ),
            ],
            options={
                "db_table": "diagram_versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagramObjectLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("node_id", models.CharField(max_length=100)),
                ("node_name", models.CharField(max_length=255)),
                ("node_type", models.CharField(max_length=100)),
                ("task", models.CharField(blank=True, default="", max_length=255)),
                (
                    "business_goal",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "business_rule",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "acceptance_criteria",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "change_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagram_links",
                        to="risks.changerequest",
                    ),
                ),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_links",
                        to="diagrams.diagram",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagram_links",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagram_links",
                        to="requirements.requirement",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagram_links",
                        to="risks.risk",
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagram_links",
                        to="stakeholders.stakeholder",
                    ),
                ),
                (
                    "user_story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagram_links",
                        to="stories.userstory",
                    ),
                ),
            ],
            options={
                "db_table": "diagram_object_links",
                "unique_together": {("diagram", "node_id")},
            },
        ),
    ]
