# Generated by Django 5.2.16 on 2026-07-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0002_alter_diagram_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagram",
            name="source_code",
            field=models.TextField(
                blank=True, default="", help_text="Mermaid or PlantUML code"
            ),
        ),
    ]
