# Generated by Django 5.2.15 on 2026-07-01 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_organizationinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "plan_tier",
                    models.CharField(
                        choices=[
                            ("FREE", "Free Tier"),
                            ("PRO", "Pro Tier"),
                            ("ENTERPRISE", "Enterprise Tier"),
                        ],
                        default="FREE",
                        max_length=50,
                    ),
                ),
                ("seats_limit", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("ai_credits_used", models.IntegerField(default=0)),
                ("ai_credits_limit", models.IntegerField(default=100)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_subscriptions",
            },
        ),
    ]
