# Generated by Django 5.2.15 on 2026-07-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsubscription",
            name="plan_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="verification_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
