# Generated by Django 5.2.15 on 2026-07-08 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_tenantsubscription_plan_verified_and_more"),
        ("organizations", "0002_organizationinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "processed_webhook_events",
            },
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Payment"),
                    ("PROCESSING", "Processing Payment"),
                    ("SUCCESS", "Active / Paid"),
                    ("FAILED", "Payment Failed"),
                    ("CANCELLED", "Subscription Cancelled"),
                    ("REFUNDED", "Subscription Refunded"),
                    ("EXPIRED", "Subscription Expired"),
                    ("DISPUTED", "Subscription Disputed"),
                ],
                default="SUCCESS",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("receipt_number", models.CharField(max_length=100, unique=True)),
                (
                    "stripe_payment_intent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_invoice",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "checkout_session",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "gst",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("coupon", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("plan", models.CharField(max_length=50)),
                ("billing_cycle", models.CharField(default="monthly", max_length=50)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gateway", models.CharField(default="STRIPE", max_length=50)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                            ("EXPIRED", "Expired"),
                            ("DISPUTED", "Disputed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice_pdf",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.tenantsubscription",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_payments",
            },
        ),
        migrations.CreateModel(
            name="PaymentAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("ip_address", models.CharField(blank=True, max_length=100, null=True)),
                ("browser", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "webhook_event",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("old_plan", models.CharField(blank=True, max_length=50, null=True)),
                ("new_plan", models.CharField(blank=True, max_length=50, null=True)),
                ("gateway_response", models.TextField(blank=True, null=True)),
                ("event_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_audit_logs",
            },
        ),
    ]
