# Generated by Django 5.2.15 on 2026-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_migrate_to_gateway_agnostic_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="paymentauditlog",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="processedwebhookevent",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="tenantsubscription",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
