# Generated by Django 5.2.16 on 2026-07-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_payment_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsubscription",
            name="daily_ai_credits_limit",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="daily_ai_credits_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="last_ai_request_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
