# Generated by Django 5.2.15 on 2026-07-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organizationinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="organizationinvitation",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
