# Generated by Django 5.2.15 on 2026-07-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
        ("stakeholders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="stakeholder_attendees",
            field=models.ManyToManyField(
                blank=True, related_name="meetings", to="stakeholders.stakeholder"
            ),
        ),
    ]
