# Generated by Django 5.2.15 on 2026-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_meeting_stakeholder_attendees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionitem",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
