# Generated by Django 5.2.15 on 2026-06-30 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stakeholder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "power",
                    models.CharField(
                        choices=[("HIGH", "High"), ("LOW", "Low")],
                        default="LOW",
                        max_length=50,
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        choices=[("HIGH", "High"), ("LOW", "Low")],
                        default="LOW",
                        max_length=50,
                    ),
                ),
                ("influence", models.IntegerField(default=3)),
                ("impact", models.IntegerField(default=3)),
                ("notes", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholders",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholders",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "stakeholders",
                "ordering": ["name"],
            },
        ),
    ]
