# Generated by Django 5.2.15 on 2026-07-15 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0004_alter_activitylog_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SRSDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("BLANK_IEEE", "Blank IEEE Template"),
                            ("AI_GENERATED", "AI Generated"),
                            ("IMPORTED_DOCX", "Imported from DOCX"),
                            ("IMPORTED_PDF", "Imported from PDF"),
                            ("DUPLICATED", "Duplicated from Existing"),
                        ],
                        default="BLANK_IEEE",
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("word_count", models.IntegerField(default=0)),
                ("reading_time_minutes", models.IntegerField(default=0)),
                ("is_ai_generated", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="srs_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_srs_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_documents",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "srs_documents",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIGenerationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("FULL_SRS", "Full IEEE SRS"),
                            ("FUNCTIONAL_REQUIREMENTS", "Functional Requirements Only"),
                            (
                                "NON_FUNCTIONAL_REQUIREMENTS",
                                "Non Functional Requirements Only",
                            ),
                            ("USE_CASES", "Use Cases"),
                            ("ACCEPTANCE_CRITERIA", "Acceptance Criteria"),
                            ("DATABASE_DESIGN", "Database Design"),
                            ("DATA_DICTIONARY", "Data Dictionary"),
                            ("UML_DESCRIPTIONS", "UML Descriptions"),
                            ("RISKS", "Risks"),
                            ("FUTURE_SCOPE", "Future Scope"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("MEETING_NOTES", "Meeting Notes"),
                            ("PROJECT_DESCRIPTION", "Project Description"),
                            ("BRD", "BRD"),
                            ("FRD", "FRD"),
                            ("USER_STORIES", "User Stories"),
                            ("REQUIREMENTS", "Requirements"),
                            ("UPLOADED_DOCUMENTS", "Uploaded Documents"),
                            ("PROMPT", "Custom Prompt"),
                        ],
                        max_length=100,
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("prompt", models.TextField(blank=True)),
                ("generated_content", models.TextField(blank=True)),
                ("ai_credits_used", models.IntegerField(default=0)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generations",
                        to="srs.srsdocument",
                    ),
                ),
            ],
            options={
                "db_table": "ai_generation_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SRSExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("DOCX", "DOCX"),
                            ("MARKDOWN", "Markdown"),
                            ("HTML", "HTML"),
                            ("JSON", "JSON"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=512)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="srs.srsdocument",
                    ),
                ),
                (
                    "exported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="srs_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "srs_exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SRSImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("DOCX", "DOCX"),
                            ("MARKDOWN", "Markdown"),
                            ("PDF", "PDF"),
                            ("IEEE_SRS", "Existing IEEE SRS"),
                        ],
                        max_length=50,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(blank=True, max_length=512)),
                ("import_status", models.CharField(default="SUCCESS", max_length=50)),
                ("error_message", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="srs.srsdocument",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="srs_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "srs_imports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SRSSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("INTRODUCTION", "1 Introduction"),
                            ("INTRODUCTION_PURPOSE", "1.1 Purpose"),
                            ("INTRODUCTION_SCOPE", "1.2 Scope"),
                            ("INTRODUCTION_AUDIENCE", "1.3 Intended Audience"),
                            ("INTRODUCTION_DEFINITIONS", "1.4 Definitions"),
                            ("INTRODUCTION_REFERENCES", "1.5 References"),
                            ("INTRODUCTION_OVERVIEW", "1.6 Document Overview"),
                            ("OVERALL_DESCRIPTION", "2 Overall Description"),
                            ("OVERALL_PERSPECTIVE", "2.1 Product Perspective"),
                            ("OVERALL_FUNCTIONS", "2.2 Product Functions"),
                            ("OVERALL_USERS", "2.3 User Classes"),
                            ("OVERALL_ENVIRONMENT", "2.4 Operating Environment"),
                            ("OVERALL_CONSTRAINTS", "2.5 Constraints"),
                            ("OVERALL_ASSUMPTIONS", "2.6 Assumptions"),
                            ("EXTERNAL_INTERFACE", "3 External Interface Requirements"),
                            ("EXTERNAL_UI", "3.1 User Interface"),
                            ("EXTERNAL_HARDWARE", "3.2 Hardware Interface"),
                            ("EXTERNAL_SOFTWARE", "3.3 Software Interface"),
                            ("EXTERNAL_COMMUNICATION", "3.4 Communication Interface"),
                            ("SYSTEM_FEATURES", "4 System Features"),
                            ("FUNCTIONAL_REQUIREMENTS", "5 Functional Requirements"),
                            (
                                "NON_FUNCTIONAL_REQUIREMENTS",
                                "6 Non Functional Requirements",
                            ),
                            ("DATABASE_REQUIREMENTS", "7 Database Requirements"),
                            ("DATA_DICTIONARY", "8 Data Dictionary"),
                            ("USE_CASES", "9 Use Cases"),
                            ("ACTIVITY_DIAGRAMS", "10 Activity Diagrams"),
                            ("SEQUENCE_DIAGRAMS", "11 Sequence Diagrams"),
                            ("CLASS_DIAGRAM", "12 Class Diagram"),
                            ("ER_DIAGRAM", "13 ER Diagram"),
                            ("STATE_DIAGRAM", "14 State Diagram"),
                            ("SYSTEM_ARCHITECTURE", "15 System Architecture"),
                            ("PERFORMANCE_REQUIREMENTS", "16 Performance Requirements"),
                            ("SECURITY_REQUIREMENTS", "17 Security Requirements"),
                            ("RISK_ANALYSIS", "18 Risk Analysis"),
                            ("FUTURE_ENHANCEMENTS", "19 Future Enhancements"),
                            ("APPENDIX", "20 Appendix"),
                            ("BIBLIOGRAPHY", "21 Bibliography"),
                            ("CUSTOM", "Custom Section"),
                        ],
                        default="CUSTOM",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_collapsed", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="srs.srsdocument",
                    ),
                ),
                (
                    "parent_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_sections",
                        to="srs.srssection",
                    ),
                ),
            ],
            options={
                "db_table": "srs_sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SRSComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("content", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="srs_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="srs.srscomment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_srs_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="srs.srsdocument",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="srs.srssection",
                    ),
                ),
            ],
            options={
                "db_table": "srs_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SRSVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("version_number", models.CharField(max_length=20)),
                ("change_summary", models.TextField(blank=True)),
                ("snapshot_data", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="srs_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="srs.srsdocument",
                    ),
                ),
            ],
            options={
                "db_table": "srs_versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SRSApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CHANGES_REQUESTED", "Changes Requested"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="srs_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="srs.srsdocument",
                    ),
                ),
            ],
            options={
                "db_table": "srs_approvals",
                "unique_together": {("document", "reviewer")},
            },
        ),
    ]
