# Generated by Django 5.2.16 on 2026-07-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0002_alter_diagram_is_deleted_and_more"),
        ("srs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="srssection",
            name="linked_diagram",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="srs_sections",
                to="diagrams.diagram",
            ),
        ),
    ]
