# Generated by Django 5.2.15 on 2026-07-01 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GapAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("current_state", models.TextField()),
                ("future_state", models.TextField()),
                ("gap_description", models.TextField()),
                ("action_plan", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDENTIFIED", "Identified"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="IDENTIFIED",
                        max_length=50,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_analyses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "gap_analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SWOTAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strengths", models.TextField(blank=True, default="")),
                ("weaknesses", models.TextField(blank=True, default="")),
                ("opportunities", models.TextField(blank=True, default="")),
                ("threats", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swot_analysis",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "SWOT Analysis",
                "verbose_name_plural": "SWOT Analyses",
                "db_table": "swot_analyses",
            },
        ),
    ]
