# Generated by Django 5.2.15 on 2026-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategic", "0003_knowledgenode_workflowexecution_knowledgeedge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijob",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="gapanalysis",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
