# Generated by Django 5.2.7 on 2026-07-01 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("jira_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "jira_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "jira_api_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "jira_project_key",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "confluence_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "confluence_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "confluence_api_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "confluence_space_key",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_config",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "integration_configs",
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("JIRA_STORIES", "Jira User Stories Sync"),
                            ("CONFLUENCE_DOC", "Confluence Document Publish"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="projects.project",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "integration_sync_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
