# Generated by Django 5.2.15 on 2026-07-01 10:40

import integrations.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconfig",
            name="confluence_api_token",
            field=integrations.models.EncryptedCharField(
                blank=True, max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="integrationconfig",
            name="jira_api_token",
            field=integrations.models.EncryptedCharField(
                blank=True, max_length=1024, null=True
            ),
        ),
    ]
