# Generated by Django 5.2.15 on 2026-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_alter_integrationconfig_confluence_api_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconfig",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
