# Generated by Django 5.2.16 on 2026-07-16 06:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_alter_integrationconfig_is_deleted_and_more"),
        ("requirements", "0002_alter_requirement_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="FigmaDesign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("figma_file_id", models.CharField(max_length=255)),
                ("figma_node_id", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=2000)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figma_designs",
                        to="requirements.requirement",
                    ),
                ),
            ],
            options={
                "db_table": "integration_figma_designs",
                "unique_together": {("figma_file_id", "figma_node_id", "requirement")},
            },
        ),
    ]
