# Generated by Django 5.2.16 on 2026-07-16 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_figmadesign"),
        ("requirements", "0002_alter_requirement_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeCommit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("repository_url", models.URLField(max_length=2000)),
                ("commit_hash", models.CharField(max_length=40)),
                ("commit_message", models.TextField(blank=True)),
                ("author_name", models.CharField(blank=True, max_length=255)),
                ("pr_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("branch_name", models.CharField(blank=True, max_length=255)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_commits",
                        to="requirements.requirement",
                    ),
                ),
            ],
            options={
                "db_table": "integration_code_commits",
                "unique_together": {("repository_url", "commit_hash", "requirement")},
            },
        ),
    ]
