# Generated by Django 5.2.15 on 2026-07-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defect",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="testcase",
            options={"ordering": ["-created_at"]},
        ),
    ]
