# Generated by Django 5.2.15 on 2026-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uat", "0002_alter_defect_options_alter_testcase_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defect",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
