# Generated by Django 5.2.15 on 2026-06-30 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("BRD", "Business Requirements Document"),
                            ("FRD", "Functional Requirements Document"),
                        ],
                        default="BRD",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("SIGNED_OFF", "Signed Off"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("signed_off_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_documents",
                        to="projects.project",
                    ),
                ),
                (
                    "signed_off_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
