# Generated by Django 5.2.15 on 2026-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_businessdocument_doc_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessdocument",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="documentapprovalhistory",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
