# Generated by Django 5.2.15 on 2026-07-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_businessdocument_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("BRD", "Business Requirements Document"),
                    ("FRD", "Functional Requirements Document"),
                    ("SWOT", "SWOT Analysis Charter"),
                    ("GAP", "GAP Analysis Framework"),
                    ("IEEE", "IEEE Standard Document"),
                ],
                default="BRD",
                max_length=20,
            ),
        ),
    ]
