# Generated by Django 5.2.16 on 2026-07-14 13:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("WELCOME", "Welcome Series"),
                            ("ONBOARDING", "Onboarding"),
                            ("FEATURE_ANNOUNCEMENT", "Feature Announcement"),
                            ("NEWSLETTER", "Newsletter"),
                            ("RE_ENGAGEMENT", "Re-engagement"),
                            ("PROMOTIONAL", "Promotional"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField(blank=True)),
                (
                    "variables",
                    models.JSONField(
                        default=dict, help_text="Available template variables"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "email_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmailList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("subscriber_count", models.IntegerField(default=0)),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="email_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_lists",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmailPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("marketing_emails", models.BooleanField(default=True)),
                ("product_updates", models.BooleanField(default=True)),
                ("newsletter", models.BooleanField(default=True)),
                ("onboarding_emails", models.BooleanField(default=True)),
                ("weekly_digest", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_preferences",
            },
        ),
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("SENDING", "Sending"),
                            ("COMPLETED", "Completed"),
                            ("PAUSED", "Paused"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_segment",
                    models.CharField(
                        blank=True, help_text="User segment to target", max_length=100
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("opened_count", models.IntegerField(default=0)),
                ("clicked_count", models.IntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="email_nurturing.emailtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "email_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Unsubscribe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("email_address", models.EmailField(max_length=254)),
                ("reason", models.TextField(blank=True)),
                (
                    "unsubscribed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unsubscribes",
                        to="email_nurturing.emailcampaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unsubscribes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "unsubscribes",
                "ordering": ["-unsubscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("OPENED", "Opened"),
                            ("CLICKED", "Clicked"),
                            ("BOUNCED", "Bounced"),
                            ("UNSUBSCRIBED", "Unsubscribed"),
                            ("COMPLAINED", "Complained"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="email_nurturing.emailcampaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_events",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="email_event_user_id_66b7cb_idx",
                    ),
                    models.Index(
                        fields=["campaign", "event_type"],
                        name="email_event_campaig_9b82e7_idx",
                    ),
                ],
            },
        ),
    ]
