# Generated by Django 5.2.15 on 2026-06-30 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requirements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("story_id", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("action", models.TextField()),
                ("benefit", models.TextField()),
                ("acceptance_criteria", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("QA", "Ready for QA"),
                            ("DONE", "Done"),
                        ],
                        default="TODO",
                        max_length=50,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        choices=[
                            (1, "1 Point"),
                            (2, "2 Points"),
                            (3, "3 Points"),
                            (5, "5 Points"),
                            (8, "8 Points"),
                            (13, "13 Points"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_stories",
                        to="requirements.requirement",
                    ),
                ),
            ],
            options={
                "db_table": "user_stories",
                "ordering": ["story_id"],
                "unique_together": {("requirement", "story_id")},
            },
        ),
    ]
