# Generated by Django 5.2.15 on 2026-07-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory",
            name="jira_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userstory",
            name="jira_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
