# Generated by Django 5.2.15 on 2026-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_userstory_jira_key_userstory_jira_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstory",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
