# Generated by Django 5.2.16 on 2026-07-15 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_alter_organization_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeatureConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(
                        choices=[
                            ("GRAMMAR", "Grammar Fix"),
                            ("REWRITE", "Rewrite"),
                            ("CHAT", "AI Chat"),
                            ("REQUIREMENT_EXTRACTION", "Requirement Extraction"),
                            ("ACCEPTANCE_CRITERIA", "Acceptance Criteria"),
                            ("USER_STORIES", "User Stories"),
                            ("UML_DIAGRAM", "UML Diagram"),
                            ("PROCESS_FLOW", "Process Flow"),
                            ("RISK_ANALYSIS", "Risk Analysis"),
                            ("GAP_ANALYSIS", "Gap Analysis"),
                            ("MEETING_ANALYSIS", "Meeting Analysis"),
                            ("PDF_ANALYSIS", "PDF Analysis"),
                            ("BRD_GENERATION", "BRD Generation"),
                            ("FRD_GENERATION", "FRD Generation"),
                            ("IEEE_SRS", "IEEE SRS Generation"),
                            ("LARGE_PDF", "Large PDF Analysis"),
                            ("COMPLEX_LOGIC", "Complex Business Logic"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("credit_cost", models.IntegerField(default=1)),
                (
                    "preferred_model",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="Model to route this feature to by default",
                        max_length=100,
                    ),
                ),
                (
                    "preferred_provider",
                    models.CharField(
                        choices=[
                            ("OPENAI", "OpenAI"),
                            ("GEMINI", "Google Gemini"),
                            ("CLAUDE", "Anthropic Claude"),
                            ("AUTO", "Auto-route (Cheapest/Fastest)"),
                        ],
                        default="AUTO",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        choices=[
                            ("OPENAI", "OpenAI"),
                            ("GEMINI", "Google Gemini"),
                            ("CLAUDE", "Anthropic Claude"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="Lower number means higher priority"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AITransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("credits_deducted", models.IntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        help_text="Estimated cost in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "latency",
                    models.FloatField(default=0.0, help_text="Latency in seconds"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CACHED", "Cached"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_logs",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
