# Generated by Django 5.2.15 on 2026-06-30 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("stakeholders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("req_id", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "req_type",
                    models.CharField(
                        choices=[
                            ("FUNCTIONAL", "Functional Requirement"),
                            ("NON_FUNCTIONAL", "Non-Functional Requirement"),
                            ("TECHNICAL", "Technical Requirement"),
                            ("UI", "User Interface"),
                        ],
                        default="FUNCTIONAL",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="projects.project",
                    ),
                ),
                (
                    "source_stakeholder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_requirements",
                        to="stakeholders.stakeholder",
                    ),
                ),
            ],
            options={
                "db_table": "requirements",
                "ordering": ["req_id"],
                "unique_together": {("project", "req_id")},
            },
        ),
    ]
