# Generated by Django 5.2.15 on 2026-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
