# Generated by Django 5.2.15 on 2026-07-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_emailotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "waitlist_signups",
                "ordering": ["-created_at"],
            },
        ),
    ]
